### ISSUE TITLE
Not work in all cases

### ISSUE THREAD

**Issue by zdm** [2072/Windowless-vimrun#1]
Hi.

Good idea, but not work in all cases.
Why not just take standard vimrun code and patch it to disable console..

**Comment by 2072** [comment]
Take a look at the standard vimrun, there isn't much in it and I haven't found a way to use the same windows API without creating a command window. Now the problem is that shell escaping doesn't work the same way depending on the API being used.

Have you tried setting the following?

`:set shellxescape-=\>`
`:set shellxescape-=\&`

As it is today it works with most of the add-ons I use daily. The add-ons having problems seem to be working "by luck" with the standard vimrun (the escape sequence they use is wrong but the `system()` API is OK with that...).

Unfortunately I don't have the time to uncover the various mysteries and magics surrounding shell escaping in Windows (it seems to be very messy) but if you got time on your end pull requests are welcomed :)

**Comment by zdm** [comment]
Hi.
I found other project.
It almost identical to original vimrun and do not quote commands, so, maybe will works everywhere. At least it works for me without adding additional shell escape commands into the vimrc.
Maybe it will be useful for you.
https://github.com/oahner/vimrun-quiet
